# Generated by Django 5.1 on 2025-01-18 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('owner_nk', models.CharField(max_length=200, null=True)),
                ('public_list', models.BooleanField()),
                ('passworded', models.BooleanField()),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author_nk', models.CharField(max_length=200, null=True)),
                ('author_ip', models.CharField(max_length=80, null=True)),
                ('message', models.TextField(max_length=1400, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.room')),
            ],
        ),
    ]
