# Generated by Django 5.1 on 2025-01-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner_nk',
        ),
        migrations.AddField(
            model_name='room',
            name='edit_code',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
